CREATE TABLE users (
    id VARCHAR(30) NOT NULL PRIMARY KEY,
    type VARCHAR(50) NOT NULL,
    role VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    is_email_verified BOOLEAN NOT NULL,
    is_phone_verified BOOLEAN NOT NULL,
    first_name VARCHAR(150) NOT NULL,
    middle_name VARCHAR(150), 
    last_name VARCHAR(150) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    username VARCHAR(16) NOT NULL UNIQUE,
    country_of_residence VARCHAR(2) NOT NULL,
    date_of_birth VARCHAR(11),
    authorization_pin VARCHAR(255),
    phone_number VARCHAR(20),
    phone_verification_code VARCHAR(6),
    phone_verification_code_expiration VARCHAR(50),
    refresh_token TEXT,
    email_verification_code VARCHAR(6),
    email_verification_code_expiration VARCHAR(50),
    avatar VARCHAR(255),
    identification_number VARCHAR(50),
    identification_document VARCHAR(150),
    identification_document_issuer VARCHAR(255),
    front_image_of_document VARCHAR(255),
    back_image_of_document VARCHAR(255),
    selfie VARCHAR(255),
    created_at VARCHAR(50) NOT NULL,
    updated_at VARCHAR(50) NOT NULL,
    tos_acceptance JSON NOT NULL,
    INDEX idx_users_table (id, username, email)
);
